export const questions = [
	{
		prompt: "Sample question: confirm you understand what's going on",
		a: 'Yup, I know I am on a timer',
		b: 'No, I am not sure what to do still',
		menteeOnly: true,
	},
	{
		qId: 1,
		prompt: 'Are you...?',
		a: 'Introvert',
		b: 'Kinda in the middle',
		c: 'Extrovert',
		linear: true,
	},
	{
		qId: 2,
		prompt: 'Do you like board games (poker, catan, spyfall, codenames, etc)?',
		a: 'Yes, I would love to play with other mentors/mentees',
		b: 'Maybe, probaby once in a while',
		c: 'Nah, I prefer other activities',
		linear: true,
	},
	{
		qId: 3,
		prompt: 'Bạn có tin vào tâm linh?',
		a: 'Có',
		b: 'Hơi hơi',
		c: 'Không',
		linear: true,
	},
	{
		qId: 4,
		prompt: 'Which Harry Potter house do you reasonate with the most?',
		a: 'Gryffindor',
		b: 'Slytherin',
		c: 'Ravenclaw',
		d: 'Hufflepuff',
		e: "I haven't watched or read Harry Potter",
	},
	{
		qId: 5,
		prompt: 'Which social media do you use the most?',
		a: 'Facebook',
		b: 'Instagram',
		c: 'YouTube',
		d: 'TikTok',
		e: 'Thread',
	},
	{
		qId: 6,
		prompt: "What's one thing you wish you had more of",
		a: 'Money',
		b: 'Fame',
		c: 'Free time',
		d: 'Health',
		e: 'Something else',
	},
	{
		qId: 7,
		prompt: 'Are you...?',
		a: 'Dog person',
		b: 'Cat person',
		c: 'Crazy person',
		d: 'Alien',
	},
	{
		qId: 8,
		prompt: 'Which one are you more struggling with?',
		a: 'Getting an interview',
		b: 'Passing an interview',
	},
	{
		qId: 9,
		prompt: 'Bạn có hay hóng hớt drama không?',
		a: 'Tôi thường là người share drama/tea trong nhóm bạn của mình',
		b: 'Tôi thường là người hóng hớt drama từ bạn mình',
		c: 'Ai kể thì nghe, chứ tôi không hóng dữ lắm',
		d: 'Lâu lâu tôi mới để ý chứ cũng không bận tâm lắm',
		e: 'Tôi ghét nghe gossip/drama',
		linear: true,
	},
	{
		qId: 10,
		prompt: 'Bạn thích mùa nào nhất?',
		a: 'Xuân',
		b: 'Hạ',
		c: 'Thu',
		d: 'Đông',
	},
	{
		qId: 11,
		prompt: 'Which show/series from below do you like the most?',
		a: 'Fellow Travellers',
		b: 'The Handmaiden',
		c: 'Heartstopper',
		d: 'Black Mirror - San Junipero',
		e: 'Call me by your name',
		f: 'Red White & Royal Blue',
		g: 'Carol',
		h: 'Drag Race',
		i: 'Dickinson',
		j: "I haven't watched any of them",
	},
	{
		qId: 12,
		prompt: 'What is your favorite project from the first cohort?',
		a: 'Bunny Lover - financial',
		b: 'Safe Travel - travel',
		c: 'Productify - productivity',
		d: "I haven't had a chance to watch the recording",
	},
	{
		qId: 13,
		prompt: 'Favorite sitcom',
		a: 'Friends',
		b: 'How I met your mother',
		c: 'Modern family',
		d: "Schitt's Creek",
		e: 'The Big Bang Theory',
		f: 'Brooklyn 99',
		g: 'None of the above',
	},
	{
		prompt: 'Hope this icebreaker made you less stressed. Did you have fun?',
		a: 'Yes, I feel better now',
		b: 'Yes, I still feel stressed though',
		c: "Nah, I didn't like this game",
		menteeOnly: true,
	},
];
