export const questions = [
	{
		prompt: "Sample question: confirm you understand what's going on",
		a: "Yup, I know I am on a timer",
		b: "No, I am not sure what to do still",
		menteeOnly: true,
	},
	{
		qId: 1,
		prompt: "Are you...?",
		a: "Introvert",
		b: "Kinda in the middle",
		c: "Extrovert",
		d: "Introvert pretending/forced to be extrovert",
		timer: 15,
	},
	{
		qId: 2,
		prompt: "Do you like  board games (poker, catan, spyfall, codenames, etc)?",
		a: "Absolutely, I volunteer to host weekly board game nights! (We are hiring)",
		b: "Yes, I would love to play",
		c: "Maybe, probaby once in a while",
		d: "Nah, I prefer other activities",
		timer: 30,
	},
	{
		qId: 3,
		prompt: "Bạn có tin vào tâm linh?",
		a: "Có",
		b: "Hơi hơi",
		c: "Không",
		d: "Hmmmm, tôi theo đạo loopy",
		e: "Tôi theo đạo con cánh cụt",
		timer: 15,
	},
	{
		qId: 4,
		prompt: "If you have a pet, it would be a...",
		a: "Dog",
		b: "Cat",
		c: "Turtle",
		d: "Unicorn",
		e: "I don't like pets",
		timer: 15,
	},
	{
		qId: 5,
		prompt: "Time complexity of searching in a binary search tree is",
		a: "O(n)",
		b: "O(log n)",
		c: "O(n log n)",
		d: "O(1)",
		e: "O(n^2)",
		menteeOnly: true,
		timer: 20,
	},
	{
		qId: 6,
		prompt: "How amazing are you at cooking?",
		a: "MasterChef level",
		b: "So good that you can bribe people with your food",
		c: "Enough to cook for myself",
		d: "Enough to not poison other",
		e: "Enough to poison my enemy",
		f: "What I cook is not edible",
		timer: 30,
	},
	{
		qId: 7,
		prompt: "Your favorite Netflix and chill genre",
		a: "Horror",
		b: "Thriller",
		c: "Drama",
		d: "Romance",
		e: "Comedy",
		f: "Documentary",
		g: "Anime",
		h: "Sci-fi",
		i: "Action",
		j: "Reality shows (The Bachelor, Love is Blind, etc)",
		k: "Competition reality shows (Survivor, Big Brother, The Traitors, etc.)",
		timer: 20,
	},
	{
		qId: 8,
		prompt: "Bạn có hay hóng hớt drama không?",
		a: "Tôi thường là người share drama/tea trong nhóm bạn của mình",
		b: "Tôi thường là người hóng hớt drama từ bạn mình",
		c: "Ai kể thì nghe, chứ tôi không hóng dữ lắm",
		d: "Lâu lâu tôi mới để ý chứ cũng không bận tâm lắm",
		e: "Tôi ghét nghe gossip/drama",
		timer: 20,
	},
	{
		qId: 9,
		prompt: "Bạn thích mùa nào nhất?",
		a: "Xuân",
		b: "Hạ",
		c: "Thu",
		d: "Đông",
	},
	{
		qId: 10,
		prompt: "Which one are you more struggling with?",
		a: "Getting an interview",
		b: "Passing behavioral interview",
		c: "Passing technical interview",
		menteeOnly: true,
		timer: 20,
	},
	{
		qId: 11,
		prompt: "What is your favorite project from 2024 Mentorship cohort?",
		a: "Flavorie - cooking",
		b: "Pick Me Food - donation",
		c: "Gathering Globe - event",
		d: "Bondscape - social",
		e: "Cupid - referral",
		f: "PeacePod - meditation",
		g: "Tourific - travel",
		h: "I didn't watch any group demo yet",
		timer: 20,
	},
	{
		qId: 12,
		prompt: "How much do you follow political news?",
		a: "I know what have been going on internationally lately",
		b: "I know what the Trump has been doing lately",
		c: "I don't actively check news but can have small discussion about",
		d: 'I would rather not talk about political stuff =")',
		e: "Only enough to know who the President is",
		f: "I actively avoid politcal news =)",
		g: "Let me keep the answer for myself",
		timer: 30,
	},
	{
		qId: 13,
		prompt: "Favorite sitcom",
		a: "Friends",
		b: "How I met your mother",
		c: "Modern family",
		d: "Schitt's Creek",
		e: "The Big Bang Theory",
		f: "Brooklyn 99",
		g: "None of the above",
		timer: 15,
	},
	{
		qId: 14,
		prompt: "In the past year, what time did you often go to bed?",
		a: "9pm - midnight",
		b: "midnight - 2am",
		c: "2am - 4am",
		d: "4am - 6am",
		e: "6am - 8am",
		f: "I don't sleep",
		timer: 15,
	},
	{
		qId: 15,
		prompt: "What OOP concept allows derived class to redefine methods?",
		a: "Encapsulation",
		b: "Abstraction",
		c: "Polymorphism",
		d: "Inheritance",
		menteeOnly: true,
		timer: 20,
	},
	{
		qId: 16,
		prompt:
			"If you could have one of these superpowers, which one would you choose?",
		a: "👀 Be invisible whenever you want",
		b: "💪🏻 Superhuman Strength",
		c: "🐶 Talk to animals",
		d: "🧠 Read minds",
		e: "🦋 Be able to fly",
		timer: 20,
	},
	{
		qId: 17,
		prompt: "How often do you call/talk to (whole) your family?",
		a: "Once or twice a day",
		b: "Once or twice a week",
		c: "Once or twice a month",
		d: "Once or twice every few months",
		e: "Maybe 2-3 times a year",
		timer: 15,
	},
	{
		qId: 18,
		prompt:
			"Nếu bạn chỉ có thể giữ lại một món sau và tất cả các món còn lại sẽ biến mất, bạn sẽ giữ lại món nào?",
		a: "Phở",
		b: "Bún bò Huế",
		c: "Bánh xèo",
		d: "Bánh chưng",
		e: "Gỏi cuốn",
		f: "Bún chả",
		g: "Bánh mì",
		h: "Cơm tấm",
		i: "Mì quảng",
		timer: 15,
	},
	{
		qId: 19,
		prompt: "If you could invest in one of these, which one would you choose?",
		a: "FAANG stonks",
		b: "Crypto - Bitcoin, Ethereum, etc.",
		c: "Meme coins - Doge, Shiba, etc.",
		d: "Real estate",
		e: "Startups",
		timer: 20,
	},
	{
		qId: 20,
		prompt: "Hope this icebreaker made you less stressed. Did you have fun?",
		a: "Yes, I feel better now",
		b: "Yes, I still feel stressed though",
		c: "Nah, I didn't like this game",
		menteeOnly: true,
		timer: 15,
	},
];
